### ISSUE TITLE
メソッド名

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/FizzBuzz#3]
メソッド名からなにをテストしているか類推できない

**Comment by tamoto-takuya** [comment]
下記の通りにメソッド名変更しています。
FizzBuzz処理→testFizzBuzzProcessing_01
Fizz処理→testFizzProcessing_01
Buzz処理→testBuzzProcessing_01
それ以外の数字→testNumberProcessing

**Comment by ghost** [comment]
01ってなに？

**Comment by tamoto-takuya** [comment]
testFizzBuzzProcessing_01の01は、FizzBuzz処理する1回目というイメージでつけました。
他も同様になります。
2回目テスト処理のときは、02というイメージです。

**Comment by ghost** [comment]
わからんな

**Comment by ghost** [comment]
https://qiita.com/alpha_pz/items/970724d69190abdea22f

**Comment by ghost** [comment]
Unitって必ずしも上から順番に実行されるわけではないよ

**Comment by ghost** [comment]
英語で表現できないなら、日本語にしてみては？

**Comment by tamoto-takuya** [comment]
「引数15の場合FizzBuzz」のように、全てメソッドを日本語に変えています。
